### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by insin** [insin/babel-plugin-react-html-attrs#10]

**Comment by ericclemmons** [comment]
Hey buddy!  Would you like some help on this?  (I'm still an avid user :D)

**Comment by insin** [comment]
Made an issue to make sure I wouldn't forget.

Forgot.

I'll cut a release later today 👍

**Comment by ericclemmons** [comment]
=*

**Comment by insin** [comment]
@ericclemmons One thing before I do: I was considering backing out [the change which added loads more attributes](https://github.com/insin/babel-plugin-react-html-attrs/commit/7b742c9a3e5f453cd557198d40acc7b9badb782a) first because I think the plugin should attempt to restrict those fixes to creation of the specific HTML elements they apply to, otherwise it increases the scope for an incredibly confusing prop-naming bug if you happen to use one of them in a custom component.

Sound good?

**Comment by ericclemmons** [comment]
@insin Sorry, I don't fully understand.  Can you give an example or describe what your preference is?

An alternative would be to keep the translations, but allow an option for the plugin to accept key/value pairs for the user to opt into.

**Comment by insin** [comment]
With the big translation list I reverted, if you wrote a component whose usage was something like `<TimeSince datetime={this.state.someDate}/>`, you'd be scratching your head for a while before figuring out this plugin was silently changing it to `dateTime`.

I could make it configurable, but `class` and `for` are the only ones which regularly bother me.

v2.1.0 is published now, but after releasing it and fixing the totally wrong tests, it seems [plugin order also matters](https://github.com/insin/babel-plugin-react-html-attrs#plugin-order-with-transform-react-inline-elements).

**Comment by ericclemmons** [comment]
Thanks, this totally makes sense!
