### ISSUE TITLE
How to edit .babelrc

### ISSUE THREAD

**Issue by zmunro** [insin/babel-plugin-react-html-attrs#11]
Where is this file? Am I supposed to create it? Should there be anything in it besides what you are saying to add??

**Comment by nazihahmed** [comment]
hi, yes you should create this file in the root directory
just call it .babelrc
here is how mine looks like:
```json
{
  "plugins": [
    "react-html-attrs",
    "transform-class-properties"
  ],
  "presets": ["react", "es2015"],
  "env": {
    "development": {
      "presets": ["react-hmre"]
    }
  }
}
```
