### ISSUE TITLE
Restrict attribute renaming by JSX element name

### ISSUE THREAD

**Issue by insin** [insin/babel-plugin-react-html-attrs#12]
**Proposal:**

- Make `class=` → `className=` apply to all JSX elements, as *everything* I've seen in the React ecosystem which takes a class uses `className=`
- Restrict `for=` → `htmlFor=` to `<label>` elements. I've seen custom label components which also use `htmlFor`, but it's still way less common than `className`.

The primary reason I created this plugin was to make it easier to copy and paste existing HTML, where `class` will be used all over the place and `for` will only be used on `<label>`. (Those are the only two React DOM attribute names which I really care about as CSS and forms are ubiquitous).

**Example in AST Explorer:**

https://astexplorer.net/#/gist/0d3e90b0821fabe17a9beafa6b78e374/cfda301987db8e71aaa9b94e0cdb60b791cfb714

---

If anyone cares about other attributes, next steps would be to bump up the number of default translations, restricted by HTML element name, and allow plugin options should you want to enable use of `for=` → `htmlFor=` everywhere or on specific custom components you use.

Pinging @ericclemmons for thoughts - are there other attribute translations you care about which you'd use the HTML version of if this was available?

**Comment by ericclemmons** [comment]
I think that makes a lot more sense.  Or restrict the conversion to HTML elements, not Components. (Capitalized vs. lowercase)

I, too, have copy/pasted lots of examples or existing markup and get bitten by this. 

`className` is definitely a must be convention for components, and I see this plugin as being a stepping-stone for users in our situation.  But, we also want to minimize the "gotchas".
