### ISSUE TITLE
Babel 6

### ISSUE THREAD

**Issue by ericclemmons** [insin/babel-plugin-react-html-attrs#2]
Leaving a note here for cross-referencing with a private repo that uses this :)

**Comment by insin** [comment]
I just published v2.0.0.

I had to remove the new es2015 preset from my initial test setup as every single plugin within it seemed to be installing a complete set of its `babel-` dependencies and the test was timing out :hurtrealbad:

**Comment by ericclemmons** [comment]
And this is why you're my fave!

Solved via dafb599. (v2.0.0)
