### ISSUE TITLE
how to handle typescript issue

### ISSUE THREAD

**Issue by PavelPolyakov** [insin/babel-plugin-react-html-attrs#8]
Hi,

Maybe someone met this before:
![image](https://cloud.githubusercontent.com/assets/839290/23464007/d01d6fb4-fe93-11e6-8506-37c3c3775038.png)

I really like this plugin comparing to the `className`, but as long as I started to use it together with `typescript` - I see this message.

Maybe there are known ways to fix it?

Regards,

**Comment by bySabi** [comment]
@PavelPolyakov did you solve it?

**Comment by PavelPolyakov** [comment]
@bySabi no, at the end I started to use `className` and other pure react properties which are available out of the box.

**Comment by bySabi** [comment]
is a shame. 
I really like to copy and paste HTML with class attrs :-)

**Comment by bySabi** [comment]
@PavelPolyakov In the end I could solve it by adding the definition of the `class` attribute to the React definitions with:

```
declare module 'react' {
  interface HTMLAttributes<T> extends AriaAttributes, DOMAttributes<T> {
    // extends React's HTMLAttributes
    class?: string;
  }
}
```

**Comment by bySabi** [comment]
@tkrotoff maybe this is useful to you too. Related to https://github.com/Microsoft/TypeScript/issues/9327

**Comment by bySabi** [comment]
and to put in the `typings` folder:

```typings\react.d.ts
import "react";

declare module "react" {
  interface HTMLAttributes<T> extends AriaAttributes, DOMAttributes<T> {
    // extends React's HTMLAttributes
    class?: string;
  }
}
```

Tested with a `next.js` based project
